### ISSUE TITLE
Img smaller than the screen

### ISSUE THREAD

**Issue by emilevictorportenart** [tholman/intense-images#22]
When the picture is smaller than the screen, there is a weird effect and the picture is not accessible anymore. 

![capture decran 2014-08-17 a 17 05 25](https://cloud.githubusercontent.com/assets/921074/3944979/5632c112-2624-11e4-9b54-a865a1dd4915.png)

Do you get the same bug?

Thanks

**Comment by lmartins** [comment]
I know this has been closed a long time ago, but there are valid use cases to set reset rules in elements like the `img` tag. For cases like those, having a classname applied to the `figure` element that is generated by the plugin would be extremely useful.
