### ISSUE TITLE
First horizontal image not loading properly

### ISSUE THREAD

**Issue by TJScalzo** [tholman/intense-images#49]
I'm not sure why, but the first image shows up black. It's very odd because the image itself is fine, it just doesn't load correctly on the page.
![screen shot 2016-06-09 at 7 17 13 pm](https://cloud.githubusercontent.com/assets/15825214/15949679/4992c3aa-2e77-11e6-8940-8488231d6479.png)
I'm not sure how this could be fixed or if there's even anything to fix. It's possible it's just my computer being old.

**Comment by tholman** [comment]
Does that happen for you on all browsers... seems fine here :/

**Comment by TJScalzo** [comment]
I see this in Safari on my 2011 MacBook Pro. My Safari version is 9.0.3 (9537.86.4.4).
I don't have any other browsers installed on my computer so I can't check if it does the same thing in other browsers.
I can tell you that it works on my phone so it's very likely that this is a problem that only I'm having. I only posted the issue saying that something was awry because it was possible for it to be a new problem that everyone was having.

**Comment by tholman** [comment]
Yeah, all good on all my browsers here... so I think it might be a you thing :(

**Comment by TJScalzo** [comment]
Yeah, it probably is. I'll close this then.
