### ISSUE TITLE
document.querySelectorAll(".viewing") is unsafe

### ISSUE THREAD

**Issue by panstav** [tholman/intense-images#52]
Querying all elements on a document with a very non-specific class, [then splicing that class out of each one of them](https://github.com/tholman/intense-images/blob/master/intense.js#L161) could lead to unexpected results in the wild :fearful:.

**Suggestion**: encapsulate all inner class names with a prefix such as `intense--`, so `.viewing` would be :sunglasses: `.intense--viewing`, `.loading` would be `.intense--loading` etc. 

I'd be happy to try PR this, if it's a valid idea..

**Comment by tholman** [comment]
Totally valid!
