### ISSUE TITLE
Error after exiting an Intensed image

### ISSUE THREAD

**Issue by nls77** [tholman/intense-images#60]
Hi,

Thank's for Intense !

I got an right after I close an image, the image is well closed but when a tried to click an other one, i got this error : 

> intense.js:1 Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

I use this js code to Intense my images : 
`var elements = document.querySelectorAll( '.item' );
Intense( elements );
`

and here is my html (i am using angular) : 
```
<div ng-repeat="galery in galerys">
   <h1 class="galeryTitle" ng-click="checked = ! checked">{{galery.gal_title}}</h1>
   <div ng-show="checked" class="owl-carousel owl-theme">
        <img on-finish-render="finish" ng-repeat="img in galery.imgs" class="item" data-title="{{img.title}}" data-caption="{{img.comment}}" ng-src="{{img.path}}"/>
   </div>
</div>
```

**Comment by tholman** [comment]
Hey mate, could you put a quick demo into a pen or something (http://codepen.io/) ... basically impossible to help you with such little info :)

**Comment by tholman** [comment]
Umm, gonna close this. Open again if you've got something! It could be a funny angular mix or something ;)

**Comment by nls77** [comment]
Hi !
I did a [fiddle](http://jsfiddle.net/nocalis/dLgpm1p2/11/) of it !

**Comment by tholman** [comment]
Ahh, you are initiating `Intense(items)` twice on the same elements, which is causing 2 of them to appear, and one of them to be removed when its clicked.

If you put a log in `$scope.$on('finish', function(ngRepeatFinishedEvent){` you'll see it fire twice.

**Comment by nls77** [comment]
If I put this 
```
var elements = document.querySelectorAll( '.item' );
Intense( elements );
```
out of 

`$scope.$on('finish', function(ngRepeatFinishedEvent){`

I get an other error 

> a.getAttribute is not a function

[Fiddle](http://jsfiddle.net/dLgpm1p2/12/)

**Comment by tholman** [comment]
This is because when you run it, the elements aren't rendered... so you're passing no elements into the function.

Here's a working version, waiting for the render to complete, and then running it. Its not ideal, but it will work with your case.

http://jsfiddle.net/wad8pbfh/

**Comment by nls77** [comment]
Ok thank's a lot for helping !
