### ISSUE TITLE
Git tags for intense-images repo

### ISSUE THREAD

**Issue by dakshshah96** [tholman/intense-images#64]
Hey @tholman,

I'd like to host your library, intense-images on [cdnjs](https://github.com/cdnjs/cdnjs) — It is one of the most famous free and public web front-end CDN services which is used by [~1,143,000 websites](https://trends.builtwith.com/cdn/CDN-JS) worldwide.

The git auto-updater for cdnjs relies on [GitHub releases](https://help.github.com/articles/creating-releases/) to recognize a release version and automatically update the library in the cdnjs repo.

If it's not too much to ask, can you please add release tags for this repo, say 1.0.0?

cdnjs/cdnjs#11266

**Comment by tholman** [comment]
This good?

https://github.com/tholman/intense-images/releases/tag/1.0.0

**Comment by dakshshah96** [comment]
@tholman The package.json mentions `1.0.3` as the version though. Will you be able to mark the previous versions also on your repo?

**Comment by tholman** [comment]
@dakshshah96 ... changed this one to 1.0.3 (that good?)

**Comment by dakshshah96** [comment]
@tholman Perfect 👍 Also, is your project hosted on npm?

**Comment by tholman** [comment]
https://www.npmjs.com/package/@tholman/intense-images

**Comment by dakshshah96** [comment]
@tholman Great, thanks a lot! I think we're good to go 😄

**Comment by tholman** [comment]
Cheers! Let me know if you need anything else :)
