### ISSUE TITLE
A better way to remove viewer

### ISSUE THREAD

**Issue by thomasgroch** [tholman/intense-images#66]
I found that when the user clicks on 2 photos quickly _intense-images_ get kind crazy losing the "open or closed" state.
I was able to reproduce the error even in the demo.
![ss](https://user-images.githubusercontent.com/67318/27711493-e62ad8cc-5cf9-11e7-8476-71f384a34746.png)

![sa](https://user-images.githubusercontent.com/67318/27711629-32e3f68a-5cfa-11e7-91f0-77204ed60530.png)

maybe do a try catch?

**Comment by tholman** [comment]
Ooh yeah, best to check that its still connected, and remove it. Or even better, remove the event handler on the first click.

Can patch up when I grab a minute!

**Comment by tiagogon** [comment]
I am having the same issue on [my page](https://trouble.place/hyper/weakness/) after clicking few images (not even at the same time). I am getting this error:

```
intense.min.js?x66689:1 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Image.B (https://trouble.place/wp-content/themes/trouble/library/js/intense-images/intense.min.js?x66689:1:5555)
B @ intense.min.js?x66689:1
```

Screencast of the issue: https://youtu.be/u4uIjbH-lBY

____
_Thanks for the great work here! <3 I love intense images to display some of my photographic series :)_

**Comment by tholman** [comment]
Pushed an update, should no longer be able to get into this position. Let me know if there are any other problems, and extra thank you for the screencast of the issue!

**Comment by tiagogon** [comment]
<3 I will text it intensively and report in case i find other issues :)
